# .github/workflows/update-activity.yml:

name: Update GitHub Activity

on:
  # schedule:
  #   - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  update-activity:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Update activity log
        uses: EvanLo62/activity-log@t1
        with:
          GITHUB_USERNAME: "EvanLo62"
          GITHUB_TOKEN: ${{ secrets.ACTIONSECRET202410 }} # Ensure this matches the secret name in repository settings
          TARGET_REPOS: '[NTUST-MIS-9002/CDVC_Schedule_2024]'
          EVENT_LIMIT: '10'
